version: '3.8'

services:
  pgsql:
    image: postgres:alpine
    container_name: 'pgsql'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: dbviraliza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: